#!/usr/bin/env bash
# Installs nginx server
sudo apt-get update

#install nginx web server
sudo apt-get -y install nginx

#listen to port 80
nc -l -p 80

# create index.html file served out by server:
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
