#!/usr/bin/env bash
# script will display Best School times
# On the 9th iteration display Best School then Hi

i=0

while [ $i -lt 10 ]
do
	if [ $i -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	i=$(( i+1 ))
done

