#!/usr/bin/env bash
# script display "Best School" 10 times
# on 4th iteration display "Bad Luck"
# on 8th iteration display "Good Luck"

i=0
while [ $((++i)) -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
