#!/usr/bin/env bash
# script display 1-20
# display bad luck from china in 4th loop
# display bad luck from japan in 9th loop
# display bad luck from italy in 17th loop

i=1
while [ $i -le 20 ]
do
	echo "$i"
	case $i in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	i=$((i+1))
done

