#!/usr/bin/env bash
# display 12 hours and 59 minutes

hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	hour=$((hour+1))

	minute=1
	while [ $minute -le 59 ]
	do
	echo $minute
	minute=$((minute+1))
	done
done
